<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smartcar">

  <xacro:property name="wheel_diameter" value="0.064" />
  <xacro:property name="wheel_width" value="0.025" />
  <xacro:property name="wheelbase_length" value="0.257" />
  <xacro:property name="wheelbase_width" value="0.17" />

  <xacro:macro name="wheel" params="prefix parent x y z">
    <link name="${prefix}_wheel">
      <visual>
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>

        </geometry>
      </visual>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${parent}" />
      <child link="${prefix}_wheel"/>
       <origin xyz="${x} ${y} ${z}" rpy="0 ${pi/2} 0"/>
    </joint>
  </xacro:macro>

  <link name="base_link">
    <visual>
      <geometry>
        <!-- <box size="${wheelbase_width} ${wheelbase_length}  0.01"/>
        <origin xyz="0 0 ${wheel_diameter / 2}"/> -->
      </geometry>
    </visual>
  </link>

    <link name="chassis_link">
    <visual>
      <geometry>
        <box size="${wheelbase_width} ${wheelbase_length}  0.01"/>
        <origin xyz="0 0 ${wheel_diameter / 2}"/>
      </geometry>
    </visual>
  </link>


  <xacro:wheel prefix="front_left"  parent="base_link" x="${wheelbase_width / 2}" y="-${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>
  <xacro:wheel prefix="front_right" parent="base_link" x="-${wheelbase_width / 2}" y="-${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>
  <xacro:wheel prefix="rear_left"   parent="base_link" x="${wheelbase_width / 2}" y="${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>
  <xacro:wheel prefix="rear_right"  parent="base_link" x="-${wheelbase_width / 2}" y="${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>

</robot>