<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="smartcar">

  <!--Xacro properties and macros--> 
  <xacro:property name="wheel_diameter" value="0.064" />
  <xacro:property name="wheel_width" value="0.025" />
  <xacro:property name="wheelbase_length" value="0.257" />
  <xacro:property name="wheelbase_width" value="0.17" />

  <xacro:macro name="wheel" params="prefix parent x y z">
    <link name="${prefix}_wheel">
      <inertial>
        <mass value="0.2"/> 
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0002"/>
        <origin xyz="0 0 0"/>
      </inertial>
      <visual>
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
      </visual>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${parent}" />
      <child link="${prefix}_wheel"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 ${pi/2} 0"/>
    </joint>
  </xacro:macro>

  <!--Body--> 
  <link name="base_link">
    <visual>
      <geometry>
      </geometry>
    </visual>
  </link>

  <link name="chassis_link">
    <inertial>
      <mass value="1.0"/> 
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.02"/>
      <origin xyz="0 0 0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${wheelbase_width} ${wheelbase_length}  0.01"/>
      </geometry>
    </visual>
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link" />
    <child link="chassis_link"/>
    <origin xyz="0 0 ${wheel_diameter / 2}"/>
  </joint>

  <xacro:wheel prefix="front_left" parent="base_link" x="${wheelbase_width / 2 + wheel_width}" y="-${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>
  <xacro:wheel prefix="front_right" parent="base_link" x="-${wheelbase_width / 2 + wheel_width}" y="-${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>
  <xacro:wheel prefix="back_left" parent="base_link" x="${wheelbase_width / 2 + wheel_width}" y="${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>
  <xacro:wheel prefix="back_right" parent="base_link" x="-${wheelbase_width / 2 + wheel_width}" y="${wheelbase_length / 2}" z="${wheel_diameter / 2}"/>

  <!--Sensors--> 

  <!--IMU-->
  <link name="imu_link">
    <!--TODO: add visual-->
  </link>
  <!-- <joint name="imu_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_link"/>
    <origin xyz="0 0 ${wheel_diameter / 2}"/>
  </joint>

  <gazebo reference="imu_link">
    <sensor type="imu" name="imu_sensor">
      <plugin name="gazebo_ros_imu_sensor" filename="libgazebo_ros_imu_sensor.so">
      <topicName>imu_data</topicName>
      <frame_name>imu_link</frame_name>
      </plugin>
    </sensor>
  </gazebo> -->

  <!--LiDAR-->
  <link name="sllidar_base_link">
    <!--TODO: add visual-->
  </link>
  <!-- <joint name="lidar_joint" type="fixed">
    <parent link="base_link" />
    <child link="sllidar_base_link"/>
    <origin xyz="0 0 ${wheel_diameter / 2}"/>
  </joint>
  <gazebo reference="sllidar_base_link">
    <sensor type="lidar" name="imu_sensor">
      <plugin name="gazebo_ros_imu_sensor" filename="libgazebo_ros_ray_sensor.so">
      <output_type>sensor_msgs/Laserscan</output_type>
      <topicName>scan</topicName>
      <frame_name>sllidar_base_link</frame_name>
      </plugin>
    </sensor>
  </gazebo> -->


</robot>
